import "./globals.css";
// import Link from "next/link";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import Timer from "./timer/Timer";

import "tailwindcss/tailwind.css";

import FinalTodo from "./todo/finalTodo";
import AuthProvider from "./AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Notes App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return ( 
    <AuthProvider>
      <html lang="en">
        <body className="grid grid-cols-9 gap-1">
          <header className="col-span-1">
            <NavBar />
          </header>
          {/* <!-- navigation --> */}
          <main className="col-start-2 col-end-7">
            <span>{children}</span>
          </main>
          <aside className="col-start-7 col-end-10">
            <Timer />
            <FinalTodo />
          </aside>
        </body>
      </html>
    </AuthProvider>
  );
}
